// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: chat.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class Chat
{
  static readonly string __ServiceName = "Chat";

  static readonly grpc::Marshaller<global::IntroRequest> __Marshaller_IntroRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IntroRequest.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::IntroResponse> __Marshaller_IntroResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IntroResponse.Parser.ParseFrom);

  static readonly grpc::Method<global::IntroRequest, global::IntroResponse> __Method_Introduce = new grpc::Method<global::IntroRequest, global::IntroResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "Introduce",
      __Marshaller_IntroRequest,
      __Marshaller_IntroResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::ChatReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of Chat</summary>
  public abstract partial class ChatBase
  {
    public virtual global::System.Threading.Tasks.Task<global::IntroResponse> Introduce(global::IntroRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for Chat</summary>
  public partial class ChatClient : grpc::ClientBase<ChatClient>
  {
    /// <summary>Creates a new client for Chat</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public ChatClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for Chat that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public ChatClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected ChatClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected ChatClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::IntroResponse Introduce(global::IntroRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return Introduce(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::IntroResponse Introduce(global::IntroRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_Introduce, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::IntroResponse> IntroduceAsync(global::IntroRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return IntroduceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::IntroResponse> IntroduceAsync(global::IntroRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_Introduce, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override ChatClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new ChatClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(ChatBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_Introduce, serviceImpl.Introduce).Build();
  }

}
#endregion
